### ISSUE TITLE
Test cnn-text-classification

### ISSUE THREAD

**Issue by brunosan** [wbg-bigdata/projectratingsml#1]
Let's do a direct port using the general IEG overall rating, and the full abstracts as "reviews" to see how it fares with basically no tweaks.

Depending how it works, we might want to test:
- [x] Using full binary map (6 -> 2 classes).
- [ ] Use all rating types.
- [ ] Only using polar values (don't use "moderately" ones for training).
- [ ] What happens if we use other fields instead of the abstract? (Like $, year, ...) This is not an ML question.
- [ ] Test [using the pretrained word2vec](https://github.com/dennybritz/cnn-text-classification-tf/issues/17#issuecomment-232218694).

**Comment by brunosan** [comment]
There is a multiclass implementation [here](https://github.com/dennybritz/cnn-text-classification-tf/issues/3), but I doubt it will helpful. If we use "highly satisfactory" class different as "satisfactory" we sparse the data too much... May be could get away not using "one hot encoder" but "2 hot"? I.e.:

``` js
* "Highly satisfactory"=      [1,1,0,0,0]
* "Satisfactory"=             [0,1,0,0,0]
* "Moderately satisfactory"=  [0,1,1,0,0]
* "Moderately unsatisfactory"=[0,0,1,1,0]
* "Unsatisfactory"=           [0,0,0,1,0]
* "Highly satisfactory"=      [0,0,0,1,1]
```

Track in #7

**Comment by brunosan** [comment]
We are dropping here, mostly because we completed the goal of understanding and learning how to code this, but the results are (unsurprisingly) negative. It's a very far fetched thing to infer IEG valuation from the abstract. Still cool project to learn about convnets for text.

**Comment by quangbemc** [comment]
* "Highly satisfactory"=      [1,1,0,0,0]
* "Satisfactory"=             [0,1,0,0,0]
* "Moderately satisfactory"=  [0,1,1,0,0]
* "Moderately unsatisfactory"=[0,0,1,1,0]
* "Unsatisfactory"=           [0,0,0,1,0]
* "Highly satisfactory"=      [0,0,0,1,
